name: HexAttributes
main: org.hexcraft.HexAttributes
version: 0.2.3
depend: [HexCore]
softdepend: [Vault]
commands:
  attribute:
    description: Base attribute command
    aliases: [a, att]
  attribute add:
    description: Add attribute
    aliases: [attribute a]
  attribute remove:
    description: Remove attribute
    aliases: [attribute r]
  attribute list:
    description: List your attributes
    aliases: [attribute l]